SELECT TABLESPACE_NAME, CONTENTS, STATUS 
FROM DBA_TABLESPACES;

SELECT FILE_NAME, TABLESPACE_NAME, BYTES/1024/1024 AS SIZE_MB 
FROM DBA_DATA_FILES
UNION ALL
SELECT FILE_NAME, TABLESPACE_NAME, BYTES/1024/1024 AS SIZE_MB 
FROM DBA_TEMP_FILES;

SELECT GROUP#, THREAD#, SEQUENCE#, MEMBERS, STATUS, ARCHIVED 
FROM V$LOG;

SELECT MEMBER, GROUP# 
FROM V$LOGFILE;

SELECT CURRENT_SCN FROM V$DATABASE;
ALTER SYSTEM SWITCH LOGFILE;

SELECT CURRENT_SCN FROM V$DATABASE;

SELECT GROUP#, THREAD#, BYTES/1024/1024 AS SIZE_MB FROM V$LOG;

ALTER DATABASE ADD LOGFILE GROUP 4 
('D:/PROGRAMS/ORACLE/ORADATA/FREE/redo04a.log', 
 'D:/PROGRAMS/ORACLE/ORADATA/FREE/redo04b.log', 
 'D:/PROGRAMS/ORACLE/ORADATA/FREE/redo04c.log') 
SIZE 50M;

SELECT LOG_MODE FROM V$DATABASE;

SELECT MAX(SEQUENCE#) FROM V$ARCHIVED_LOG;

SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
SELECT STATUS FROM V$INSTANCE;


ALTER DATABASE ARCHIVELOG;
ALTER DATABASE NOARCHIVELOG;

ALTER DATABASE OPEN;

ALTER SYSTEM ARCHIVE LOG CURRENT;

SHOW PARAMETER log_archive_dest;

SHOW PARAMETER control_files;

SELECT * FROM V$CONTROLFILE;
