SHOW USER;

GRANT DBA TO ADMIN;
GRANT RESOURCE TO ADMIN;
GRANT UNLIMITED TABLESPACE TO ADMIN;
GRANT CREATE TABLE TO U1_VVV_PDB;
grant create USER  to ADMIN
GRANT CREATE SESSION TO U1_VVV_PDB;
ALTER USER U1_VVV_PDB QUOTA 100M ON VVV_TBS;

SELECT * FROM V$PWFILE_USERS WHERE USERNAME = 'ADMIN';

show CON_NAME
ALTER SESSION SET CONTAINER = VVV_PDB;
ALTER SESSION SET CONTAINER = CDB$ROOT;

SELECT USERNAME, ACCOUNT_STATUS FROM DBA_USERS WHERE USERNAME = 'U1_VVV_PDB';
SELECT GRANTED_ROLE FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'U1_VVV_PDB';
SELECT STATUS FROM V$INSTANCE;
ALTER DATABASE OPEN;









SELECT PDB_ID, PDB_NAME, STATUS FROM CDB_PDBS;

CREATE TABLESPACE VVV_TBS DATAFILE 'C:\VVVFiles\VVV_TBS.dbf' SIZE 100M AUTOEXTEND ON;
drop tablespace XXX_TBS

create role VVV_ROLE
CREATE PROFILE VVV_PROFILE LIMIT PASSWORD_LIFE_TIME 90;

CREATE USER U1_VVV_PDB IDENTIFIED BY "password"
DEFAULT TABLESPACE VVV_TBS
PROFILE VVV_PROFILE;
  
 drop user U1_VVV_PDB

  
GRANT VVV_ROLE TO U1_VVV_PDB;


SELECT USERNAME FROM DBA_USERS;
SELECT GRANTEE, PRIVILEGE FROM DBA_SYS_PRIVS;

CREATE TABLE XXX_table (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(100),
    created_at DATE DEFAULT SYSDATE
);

INSERT INTO XXX_table (id, name) VALUES (1, 'Первый элемент');
INSERT INTO XXX_table (id, name) VALUES (2, 'Второй элемент');
COMMIT;
SELECT * FROM XXX_table;

SELECT TABLESPACE_NAME FROM DBA_TABLESPACES;
SELECT FILE_NAME, TABLESPACE_NAME, STATUS FROM DBA_DATA_FILES;
SELECT FILE_NAME, TABLESPACE_NAME FROM DBA_TEMP_FILES;

SELECT * FROM DBA_ROLE_PRIVS;

SELECT * FROM DBA_PROFILES;
SELECT USERNAME, DEFAULT_TABLESPACE, PROFILE FROM DBA_USERS;

CREATE USER C##VVV IDENTIFIED BY Vlad060606 CONTAINER=ALL;
GRANT CREATE SESSION TO C##VVV;
GRANT CREATE TABLE TO C##VVV;

CREATE TABLE customers (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(100),
    email VARCHAR2(100)
);
INSERT INTO customers (id, name, email) VALUES (1, 'Alice', 'alice@example.com');
INSERT INTO customers (id, name, email) VALUES (2, 'Bob', 'bob@example.com');
COMMIT;
SELECT OBJECT_NAME, OBJECT_TYPE FROM USER_OBJECTS;



CREATE USER C##HBA_CORE IDENTIFIED BY mypassword;
GRANT CONNECT, RESOURCE TO C##HBA_CORE;
GRANT RESTRICTED SESSION TO C##HBA_CORE;
grant create session    to C##HBA_CORE

SELECT SID, SERIAL#, USERNAME, OSUSER, MACHINE, PROGRAM, LOGON_TIME
FROM V$SESSION 
WHERE CON_ID = 1;